package com.stpl.pms.utility;

public enum PracticeTxType {
	PRACTICE_TO_CASH, PRACTICE_DEPOSIT, PRACTICE_WAGER, PRACTICE_WINNING, TRANSFER_FROM_SUBWALLET, TRANSFER_TO_SUBWALLET,
	SUBWALLET_WAGER, SUBWALLET_WINNING,PRACTICE_WAGER_REFUND,SUBWALLET_WAGER_REFUND,
}
