package com.stpl.pms.utility;

public enum TxnRequestType {
	WAGER,WINNING,TRANSFER_FROM_SUBWALLET,TRANSFER_TO_SUBWALLET,WAGER_REFUND, WAGER_CONFIRMATION, GET_BALANCE, GET_TXN_STATUS,PAY_CORRECTION,REFUND_AFTER_CONFIRM,
}
