package com.stpl.pms.utility;

public enum TxType {
	SALE, WIN, CANCLE, DEPOSIT, WITHDRAWAL, BONUS, BONUS_TRANSFER, BONUS_EXPIRED, TRANSFER_FROM_SUBWALLET, TRANSFER_TO_SUBWALLET, SUBWALLET_WAGER, 
		SUBWALLET_WINNING, WAGER_REFUND,SUBWALLET_WAGER_REFUND, DEPOSIT_AGAINST_CANCEL, DEBIT_CORRECTION,CREDIT_CORRECTION,INACTIVE_SUBWALLET,TRANSFER_TO_SUBWALLET_POKER,TRANSFER_TO_REFUND,COMM_TXN
}
