package com.stpl.pms.utility;

public enum WeaverServiceRequestType {
	REGISTRATION, USER_AVAILABILITY, EMAIL_AVAILABILITY, MOBILE_AVAILABILITY, DEPOSIT,WITHDRAWAL_SUCCESS,USER_DEPOSIT_AVAILABILITY, PLAYER_AFFILIATE_BINDING, NG_DEPOSIT_REPORT, NG_WAGER_REPORT, USER_NAME_CHANGE,GET_PLAYER_INFO,FORGOT_PASSWORD
}
